# site settings
title: Computer and Systems Information
subtitle: Learning Modules ranging from Programming to Math and Science
email: ashinhust.brass@gmail.com
description: Below you will find links containing all of the information that I have gathered upon multiple subjects from Programming to Math and Physics.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: www.markinfo.dev
author: Mark Ashinhust
phone: +1 (623) 523 2880

# homepage tiles
tiles-source: pages
tiles-count: 6

# social settings
500px_url:
github_url: https://github.com/Markay12
linkedin_url: https://www.linkedin.com/in/mark-ashinhust-3aa5b9193/

# build settings
markdown: kramdown

sass:
  style: compressed
